#!/bin/bash -l
##SBATCH --job-name=wind-observation-validate_ffc
##SBATCH --job-name=wind-observation-test_ffc
#SBATCH --job-name=solar-fusion-test_envelop
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=20
#SBATCH --time=24:00:00
#SBATCH -p batch
##SBATCH --mem=187G
##SBATCH --output=res.txt
##SBATCH --mail-type=BEGIN,END
##SBATCH --mail-user=guillermoterren@ucsb.edu
#SBATCH --output=%x.%j.out

cd /home/gterren/dynamic_update/functional_forecast_dynamic_update
source activate fda

#mpirun -np 20 python validate_ffc.py solar fusion $1 $2
#mpirun -np 20 python test_ffc.py wind observation $1
#mpirun -np 20 python validate_ffc.py wind observation $1 72

#mpirun -np 20 python validate_envelop.py solar fusion $1 $2 
mpirun -np 20 python test_envelop.py solar fusion $1 $2